### ISSUE TITLE
10.1.5 Broken

### ISSUE THREAD

**Issue by dfurray** [Urtgard/Annene#9]
1x Annene/Annene.lua:417: attempt to index field '?' (a nil value)
[string "@Annene/Annene.lua"]:417: in function `?'
[string "@Masque/Libs/CallbackHandler-1.0-8/CallbackHandler-1.0.lua"]:109: in function <...que/Libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:109>
[string "=[C]"]: ?
[string "@Masque/Libs/CallbackHandler-1.0-8/CallbackHandler-1.0.lua"]:19: in function <...que/Libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:15>
[string "@Masque/Libs/CallbackHandler-1.0-8/CallbackHandler-1.0.lua"]:54: in function `Fire'
[string "@ElvUI_Libraries/Core/Ace3/AceEvent-3.0-4/AceEvent-3.0.lua"]:120: in function <...UI_Libraries/Core/Ace3/AceEvent-3.0/AceEvent-3.0.lua:119>

Locals:
self = <table> {
 SetDefaultModuleLibraries = <function> defined @Masque/Libs/AceAddon-3.0/AceAddon-3.0.lua:363
 OnInitialize = <function> defined @Annene/Annene.lua:4
 UnregisterAllEvents = <function> defined @Masque/Libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:164
 EnableModule = <function> defined @Masque/Libs/AceAddon-3.0/AceAddon-3.0.lua:328
 modules = <table> {
 }
 GetModule = <function> defined @Masque/Libs/AceAddon-3.0/AceAddon-3.0.lua:206
 IterateEmbeds = <function> defined @Masque/Libs/AceAddon-3.0/AceAddon-3.0.lua:438
 anchor = AnneneAnchor {
 }
 defaultModuleLibraries = <table> {
 }
 optionsFrame = Frame {
 }
 PetBattleFrameSetStyle = <function> defined @Annene/Annene.lua:410
 options = <table> {
 }
 SetDefaultModulePrototype = <function> defined @Masque/Libs/AceAddon-3.0/AceAddon-3.0.lua:405
 name = "Annene"
 IsEnabled = <function> defined @Masque/Libs/AceAddon-3.0/AceAddon-3.0.lua:447
 orderedModules = <table> {
 }
 DisableModule = <function> defined @Masque/Libs/AceAddon-3.0/AceAddon-3.0.lua:346
 otherAddons = <table> {
 }
 RegisterMessage = <function> defined @Masque/Libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:80
 UnregisterMessage = <function> defined @Masque/Libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:143
 PetBattleFrameSetPosition = <function> defined @Annene/Annene.lua:630
 IsModule = <function> defined @Masque/Libs/AceAddon-3.0/AceAddon-3.0.lua:464
 db = <table> {
 }
 SendMessage = <function> defined @Masque/Libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:49
 tooltipAnchor = AnneneTooltipAnchor {
 }
 defaults = <table> {
 }
 SetEnabledState = <function> defined @Masque/Libs/AceAddon-3.0/AceAddon-3.0.lua:420
 baseName = "Annene"
 enabledState = true
 AddonLoaded = <function> defined @Annene/Annene.lua:634
 RegisterEvent = <function> defined @Masque/Libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:80
 UnregisterAllMessages = <function> defined @Masque/Libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:164
 BuildOptionsTable = <function> defined @Annene/Annene.lua:135
 OnEnable = <function> defined @Annene/Annene.lua:33
 Enable = <function> defined @Masque/Libs/AceAddon-3.0/AceAddon-3.0.lua:290
 IterateModules = <function> defined @Masque/Libs/AceAddon-3.0/AceAddon-3.0.lua:433
 NewModule = <function> defined @Masque/Libs/AceAddon-3.0/AceAddon-3.0.lua:231
 SetDefaultModuleState = <function> defined @Masque/Libs/AceAddon-3.0/AceAddon-3.0.lua:383
 GetName = <function> defined @Masque/Libs/AceAddon-3.0/AceAddon-3.0.lua:275
 defaultModuleState = true
 UnregisterEvent = <function> defined @Masque/Libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:143
 Disable = <function> defined @Masque/Libs/AceAddon-3.0/AceAddon-3.0.lua:310
}
(*temporary) = nil
(*temporary) = nil
(*temporary) = 1
(*temporary) = <userdata>
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index field '?' (a nil value)"

**Comment by Urtgard** [comment]
Thanks for the info. I haven't had time to test the patch yet.

**Comment by Urtgard** [comment]
Can you confirm this happens only in combination with ElvUi? Without ElvUi I didn't see the error.

**Comment by dfurray** [comment]
It doesn't happen since the lastest update to ElvUI.
